require:
  - standard

plugins:
  - rubocop-rspec
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - public/**/*
    - vendor/**/*
  TargetRubyVersion: 3.1.4

RSpec:
  Enabled: true

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - given
    - and
    - for
    - by

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
