require 'head_music/version'

require 'active_support/core_ext/module/delegation'
require 'active_support/core_ext/string/access'
require 'humanize'

require 'head_music/accidental'
require 'head_music/circle'
require 'head_music/clef'
require 'head_music/consonance'
require 'head_music/functional_interval'
require 'head_music/instrument'
require 'head_music/interval'
require 'head_music/key_signature'
require 'head_music/letter_name'
require 'head_music/meter'
require 'head_music/note'
require 'head_music/octave'
require 'head_music/pitch_class'
require 'head_music/pitch'
require 'head_music/quality'
require 'head_music/rhythmic_unit'
require 'head_music/rhythmic_value'
require 'head_music/scale'
require 'head_music/scale_type'
require 'head_music/spelling'
require 'head_music/staff'
require 'head_music/utilities/hash_key'

module HeadMusic
end
